### ISSUE TITLE
MissingMappingFileError

### ISSUE THREAD

**Issue by williballenthin** [fireeye/flare-wmi#5]
via @BannersSecret in #2:

Thanks for coming back to me so quickly. When I run that, I get:

```
Traceback (most recent call last):
  File "samples/list.py", line 29, in <module>
    main(*sys.argv[1:])
  File "samples/list.py", line 22, in main
    tree = Tree(c)
  File "/usr/local/lib/python2.7/dist-packages/cim/objects.py", line 1577, in __init__
    self._object_resolver = ObjectResolver(cim, Index(cim.cim_type, cim.logical_index_store))
  File "/usr/local/lib/python2.7/dist-packages/funcy/objects.py", line 25, in __get__
    res = instance.__dict__[self.fget.__name__] = self.fget(instance)
  File "/usr/local/lib/python2.7/dist-packages/cim/cim.py", line 774, in logical_index_store
    return LogicalIndexStore(self, self._index_file_path, self.index_mapping)
  File "/usr/local/lib/python2.7/dist-packages/cim/cim.py", line 765, in index_mapping
    _, current_index_mapping = self.mappings
  File "/usr/local/lib/python2.7/dist-packages/funcy/objects.py", line 25, in __get__
    res = instance.__dict__[self.fget.__name__] = self.fget(instance)
  File "/usr/local/lib/python2.7/dist-packages/cim/cim.py", line 746, in mappings
    fp = self._current_mapping_file
  File "/usr/local/lib/python2.7/dist-packages/funcy/objects.py", line 25, in __get__
    res = instance.__dict__[self.fget.__name__] = self.fget(instance)
  File "/usr/local/lib/python2.7/dist-packages/cim/cim.py", line 739, in _current_mapping_file
    raise MissingMappingFileError()
cim.cim.MissingMappingFileError
```

The 'wbem' folder contains all the files extracted from that folder on the suspect machine. Have I done that right.....?

Thanks again for your help.

**Comment by williballenthin** [comment]
@BannersSecret: Could you share the list of files in the `wbem` directory? I'm mostly looking to confirm the existence of files like "MAPPING1.MAP" and friends.

**Comment by BannersSecret** [comment]
Thanks again, and I'm happy (and ashamed) to report that this is totally user idiotness. I wasn't specifying the Repository folder, just straight up wbem. Working without error now. Sorry....

**Comment by williballenthin** [comment]
Great! We'll keep reporting any issues you encounter and we'll be happy to help.

**Comment by BannersSecret** [comment]
Thanks a lot!
